<a href="https://colab.research.google.com/github/Sushmakumar369/Assignments/blob/main/numpy_pandas_casestudy_questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 📚 **NumPy, Pandas, Matplotlib, and Seaborn Practice Questions**
---
This notebook contains four sets of practice questions covering NumPy, Pandas, Matplotlib, and Seaborn. Complete the tasks below and run the respective cells.

## 🧠 **Question 1: NumPy Array Manipulation**
1. Create a 1D NumPy array with integers from **1 to 24**.  
2. Reshape the array into a **4x6 matrix**.  
3. Extract the **third row** and **second column** from the reshaped array.  
4. Transpose the matrix and display the result.

In [ ]:
# Solution for Question 1
import numpy as np

# CREATING 1D ARRAY
data=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24]
a1=np.array(data)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
# RESHAPING THE ARRAY
a2=a1.reshape(4,6)
a2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [ ]:
# EXTRACT THE THIRD ROW
a2[2,:]

array([13, 14, 15, 16, 17, 18])

In [ ]:
# EXTRACT THE SECOND COLUMN
a2[:,1]

array([ 2,  8, 14, 20])

In [ ]:
# TRANSPOSING THE ARRAY
np.transpose(a2)

array([[ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23],
       [ 6, 12, 18, 24]])

## 🧠 **Question 2: Array Element Extraction**
1. Create a **5x5 NumPy array** with random integers between **10 and 100**.  
2. Extract all the **even numbers** from the array.  
3. Replace all numbers **greater than 50** with **0**.  
4. Extract the diagonal elements of the array.

In [ ]:
# Solution for Question 2
import numpy as np

# CREATING 5X5 ARRAY
data1=[[10,12,15,18,20],[25,26,28,30,32],[35,40,45,48,51],[52,54,56,59,60],[62,63,65,68,69]]
a3=np.array(data1)
a3

array([[10, 12, 15, 18, 20],
       [25, 26, 28, 30, 32],
       [35, 40, 45, 48, 51],
       [52, 54, 56, 59, 60],
       [62, 63, 65, 68, 69]])

In [ ]:
# EVEN NUMBERS
a3[a3%2==0]

array([10, 12, 18, 20, 26, 28, 30, 32, 40, 48, 52, 54, 56, 60, 62, 68])

In [ ]:
# REPLACING NUMBERS >50 WITH 0
a3[a3>50]=0
a3

array([[10, 12, 15, 18, 20],
       [25, 26, 28, 30, 32],
       [35, 40, 45, 48,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [ ]:
# EXTRACTING DIAGONAL ELEMENTS
np.diagonal(a3)

array([10, 26, 45,  0,  0])

## 🧠 **Question 3: DataFrame Creation and Operations (Pandas)**
1. Create a Pandas DataFrame containing the following data:

| Student_ID | Name   | Subject | Marks |
|------------|--------|---------|-------|
| 1          | Alice  | Math    | 88    |
| 2          | Bob    | Science | 75    |
| 3          | Carol  | History | 92    |
| 4          | David  | Math    | 85    |
| 5          | Eva    | Science | 90    |

2. Find the **average marks** for each subject.  
3. Add a new column named **Grade** based on the marks:
- Marks ≥ 90 → A
- Marks ≥ 80 → B
- Marks ≥ 70 → C
- Else → D

In [ ]:
# Solution for Question 3
import pandas as pd

# CREATING A DATAFRAME

data={'Student_ID': [1,2,3,4,5],  'Name':['Alice',  'Bob', 'Carol', 'David', 'Eva'],    'Subject':['Math', 'Science','History','Math', 'Science'], 'Marks':[88, 75,92,85,90]}
marklist=pd.DataFrame(data)
marklist

Student_ID   Name  Subject  Marks
0           1  Alice     Math     88
1           2    Bob  Science     75
2           3  Carol  History     92
3           4  David     Math     85
4           5    Eva  Science     90

In [ ]:
# FINDING AVERAGE MARKS
average_marks=marklist.groupby('Subject') ['Marks'].mean()
average_marks

Subject
History    92.0
Math       86.5
Science    82.5
Name: Marks, dtype: float64

In [ ]:
# ADDING AND INSERTING VALUES IN A NEW COLUMN GRADE
marklist_1=pd.DataFrame(data, columns=['Student_ID', 'Name', 'Subject', 'Marks', 'Grade'])
marklist_1['Grade']=['B', 'C', 'A', 'B', 'A']
marklist_1

Student_ID   Name  Subject  Marks Grade
0           1  Alice     Math     88     B
1           2    Bob  Science     75     C
2           3  Carol  History     92     A
3           4  David     Math     85     B
4           5    Eva  Science     90     A

## 🧠 **Question 4: Dataset Analysis (Pandas, Matplotlib, Seaborn)**
Use the dataset `diabetes.csv` and perform the following tasks:

1. Display the **BMI** and **Blood Pressure** for samples with **index ranging from 20 to 40**.  
2. Find how many patients have **BMI > 30**.  
3. Find the **mean and standard deviation** of the **Glucose** levels.  
4. Plot a **boxplot** for the column **Insulin**.  
5. Create a **heatmap** showing the correlation between the numerical columns in the dataset.

In [ ]:
# Solution for Question 4
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Displaying BMI AND BLOODPRESSURE
data=pd.read_csv('/content/diabetes_model.csv')
column=data.loc[20:40,['BMI','BloodPressure']]
column

BMI  BloodPressure
20  34.2             70
21  35.0             82
22  30.5             74
23  31.6             70
24  22.1             62
25  27.1             88
26  43.5             60
27  36.0             75
28  34.2             70
29  36.5             90
30  30.4             86
31  43.3             78
32  37.7             68
33  23.0             78
34  46.1             78
35  32.8             78
36  43.3             30
37  26.5             68
38  28.0              0
39  46.8             84
40  24.4             55

In [ ]:
BMI=data['BMI'] > 30
count=len(BMI)
count

614